### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by forteller** [xavivars/xv-random-quotes#11]
Hi. Thank you for a great plugin! I use it to power my random quote generator website https://www.godhetstyranniet.no/

Unfortunately the plugin has stopped working, now only displaying one quote, never changing it no matter how many times you reload it.

The interesting thing is that it still shows a different quote to each browser visiting the page, but after showing you that quote, it never changes it.

I recently updated my blog to PHP 7.2, and I didn't notice this error until after that. But then I downgraded to 5.6 again, and it's still just the same. So I don't know if that was related at all or not. Anyways, that's the only change I've done which seems relevant.

Hope there's anything you can do to help! Thank you!

**Comment by xavivars** [comment]
Hello,

It seems you're using "WP-Super-Cache". That plugin completely caches the page, so reloading will show you exactly the same thing.

You can also reload the quote by clicking a link, but it seems you added a "space" to the text you want to appear to change the link, so it's invisible

![image](https://user-images.githubusercontent.com/134083/58036535-a09d8a00-7b2b-11e9-9158-d75c88fc8683.png)

**Comment by forteller** [comment]
Oh, wow. That was stupid of me. Thank you very much! :D
